In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3],dtype=float)

In [3]:
a

array([1., 2., 3.])

In [4]:
a[a>2]

array([3.])

In [6]:
dt=np.dtype([('age',np.int8)])

In [7]:
a=np.array([(20,),(12,),(73,)],dtype=dt)

In [8]:
a

array([(20,), (12,), (73,)], dtype=[('age', 'i1')])

In [9]:
a['age']

array([20, 12, 73], dtype=int8)